-- Gongsoop server + study-space schema for Oracle 19c
-- Fresh development schema only. Do not run when these tables already exist.

CREATE SEQUENCE seq_study_room START WITH 1 INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE seq_study_channel START WITH 1 INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE seq_seat START WITH 1 INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE seq_study_session START WITH 1 INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE seq_seat_occupancy START WITH 1 INCREMENT BY 1 CACHE 20 NOCYCLE;

CREATE TABLE members (
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR2(100 CHAR) NOT NULL,
    birthdate DATE NOT NULL,
    email VARCHAR2(255 CHAR) NOT NULL,
    password VARCHAR2(255 CHAR) NOT NULL,
    user_role VARCHAR2(20 CHAR) DEFAULT 'USER' NOT NULL,
    is_deleted NUMBER(1) DEFAULT 0 NOT NULL,
    CONSTRAINT pk_members PRIMARY KEY (user_id),
    CONSTRAINT uq_members_email UNIQUE (email),
    CONSTRAINT ck_member_role CHECK (user_role IN ('USER', 'ADMIN')),
    CONSTRAINT ck_member_deleted CHECK (is_deleted IN (0, 1))
);

CREATE TABLE study_room (
    study_room_id NUMBER(19) NOT NULL,
    room_name VARCHAR2(100 CHAR) NOT NULL,
    map_no NUMBER(1) NOT NULL,
    is_active CHAR(1) DEFAULT 'Y' NOT NULL,
    CONSTRAINT pk_study_room PRIMARY KEY (study_room_id),
    CONSTRAINT uk_study_room_name UNIQUE (room_name),
    CONSTRAINT uk_study_room_map UNIQUE (map_no),
    CONSTRAINT ck_study_room_map CHECK (map_no BETWEEN 1 AND 4),
    CONSTRAINT ck_study_room_active CHECK (is_active IN ('Y', 'N'))
);

CREATE TABLE study_channel (
    study_channel_id NUMBER(19) NOT NULL,
    study_room_id NUMBER(19) NOT NULL,
    channel_no NUMBER(1) NOT NULL,
    channel_name VARCHAR2(100 CHAR) NOT NULL,
    is_active CHAR(1) DEFAULT 'Y' NOT NULL,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    CONSTRAINT pk_study_channel PRIMARY KEY (study_channel_id),
    CONSTRAINT fk_study_channel_room FOREIGN KEY (study_room_id)
        REFERENCES study_room (study_room_id),
    CONSTRAINT uk_study_channel_room_no UNIQUE (study_room_id, channel_no),
    CONSTRAINT uk_study_channel_room_name UNIQUE (study_room_id, channel_name),
    CONSTRAINT ck_study_channel_no CHECK (channel_no BETWEEN 1 AND 3),
    CONSTRAINT ck_study_channel_active CHECK (is_active IN ('Y', 'N'))
);

CREATE TABLE seat (
    seat_id NUMBER(19) NOT NULL,
    study_room_id NUMBER(19) NOT NULL,
    seat_no NUMBER(5) NOT NULL,
    is_active CHAR(1) DEFAULT 'Y' NOT NULL,
    CONSTRAINT pk_seat PRIMARY KEY (seat_id),
    CONSTRAINT fk_seat_study_room FOREIGN KEY (study_room_id)
        REFERENCES study_room (study_room_id),
    CONSTRAINT uk_seat_room_no UNIQUE (study_room_id, seat_no),
    CONSTRAINT ck_seat_no CHECK (seat_no > 0),
    CONSTRAINT ck_seat_active CHECK (is_active IN ('Y', 'N'))
);

CREATE TABLE study_session (
    study_session_id NUMBER(19) NOT NULL,
    user_id NUMBER NOT NULL,
    study_channel_id NUMBER(19) NOT NULL,
    seat_id NUMBER(19) NOT NULL,
    subject VARCHAR2(50 CHAR) NOT NULL,
    study_date DATE NOT NULL,
    status_code VARCHAR2(20 CHAR) NOT NULL,
    resume_status_code VARCHAR2(12 CHAR),
    started_at TIMESTAMP NOT NULL,
    last_resumed_at TIMESTAMP,
    paused_at TIMESTAMP,
    pause_deadline_at TIMESTAMP,
    ended_at TIMESTAMP,
    accumulated_seconds NUMBER(19) DEFAULT 0 NOT NULL,
    end_reason_code VARCHAR2(20 CHAR),
    version_no NUMBER(19) DEFAULT 0 NOT NULL,
    CONSTRAINT pk_study_session PRIMARY KEY (study_session_id),
    CONSTRAINT fk_session_member FOREIGN KEY (user_id) REFERENCES members (user_id),
    CONSTRAINT fk_session_channel FOREIGN KEY (study_channel_id)
        REFERENCES study_channel (study_channel_id),
    CONSTRAINT fk_session_seat FOREIGN KEY (seat_id) REFERENCES seat (seat_id),
    CONSTRAINT ck_session_status CHECK (status_code IN (
        'RUNNING', 'PAUSED', 'DISCONNECTED', 'COMPLETED',
        'AUTO_TERMINATED', 'FORCED_TERMINATED'
    )),
    CONSTRAINT ck_session_resume CHECK (
        resume_status_code IS NULL OR resume_status_code IN ('RUNNING', 'PAUSED')
    ),
    CONSTRAINT ck_session_seconds CHECK (accumulated_seconds >= 0),
    CONSTRAINT ck_session_end_reason CHECK (
        end_reason_code IS NULL OR end_reason_code IN (
            'USER_EXIT', 'PAUSE_TIMEOUT', 'RECONNECT_TIMEOUT', 'ADMIN_FORCE_EXIT'
        )
    )
);

CREATE TABLE seat_occupancy (
    seat_occupancy_id NUMBER(19) NOT NULL,
    study_channel_id NUMBER(19) NOT NULL,
    seat_id NUMBER(19) NOT NULL,
    user_id NUMBER NOT NULL,
    study_session_id NUMBER(19) NOT NULL,
    occupied_at TIMESTAMP NOT NULL,
    last_seen_at TIMESTAMP NOT NULL,
    disconnected_at TIMESTAMP,
    reconnect_deadline_at TIMESTAMP,
    version_no NUMBER(19) DEFAULT 0 NOT NULL,
    CONSTRAINT pk_seat_occupancy PRIMARY KEY (seat_occupancy_id),
    CONSTRAINT fk_occupancy_channel FOREIGN KEY (study_channel_id)
        REFERENCES study_channel (study_channel_id),
    CONSTRAINT fk_occupancy_seat FOREIGN KEY (seat_id) REFERENCES seat (seat_id),
    CONSTRAINT fk_occupancy_member FOREIGN KEY (user_id) REFERENCES members (user_id),
    CONSTRAINT fk_occupancy_session FOREIGN KEY (study_session_id)
        REFERENCES study_session (study_session_id),
    CONSTRAINT uk_occupancy_channel_seat UNIQUE (study_channel_id, seat_id),
    CONSTRAINT uk_occupancy_member UNIQUE (user_id),
    CONSTRAINT uk_occupancy_session UNIQUE (study_session_id)
);

CREATE INDEX idx_seat_room ON seat (study_room_id);
CREATE INDEX idx_channel_room ON study_channel (study_room_id);
CREATE INDEX idx_session_member_date ON study_session (user_id, study_date);
CREATE INDEX idx_session_pause_deadline ON study_session (pause_deadline_at);
CREATE INDEX idx_occupancy_reconnect ON seat_occupancy (reconnect_deadline_at);

CREATE UNIQUE INDEX uk_session_active_member
    ON study_session (
        CASE WHEN status_code IN ('RUNNING', 'PAUSED', 'DISCONNECTED') THEN user_id END
    );

CREATE UNIQUE INDEX uk_session_active_channel_seat
    ON study_session (
        CASE WHEN status_code IN ('RUNNING', 'PAUSED', 'DISCONNECTED')
            THEN study_channel_id END,
        CASE WHEN status_code IN ('RUNNING', 'PAUSED', 'DISCONNECTED')
            THEN seat_id END
    );

-- Application rule: a channel and seat used together must belong to the same study_room.
